//Dynamic route

import { results, handler } from "../api/index";
import Head from "next/head";
import Link from "next/link";
import Layout from "components/Layout";
import List from "components/List";

//NY times API for fetching data
const API_KEY = "plbCTSLsncuKnvXzlc8Cf02XQkGGVuz6";

export default function Posts(props) {
  return (
    <Layout>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <List {...props} />
    </Layout>
  );
}

export async function getStaticPaths() {
  const SECTIONS_URL = `https://api.nytimes.com/svc/news/v3/content/section-list.json?api-key=${API_KEY}`;
  const section_results = await handler(SECTIONS_URL);
  return {
    paths: section_results.map((result) => {
      return { params: { section: result.section } };
    }),
    fallback: true,
  };
}

//Prerender data on request time based on user input
export async function getStaticProps({ params }) {
  const TOP_STORIES_URL = `https://api.nytimes.com/svc/news/v3/content/nyt/${params.section}.json?api-key=${API_KEY}`;

  const results = await handler(TOP_STORIES_URL);
  const formatedResults = JSON.parse(results);
  return {
    props: {
      results: formatedResults,
      title: "Section: " + params.section,
    },
  };
}
