//Dynamic route

import { handler } from "../api/index";
import Head from "next/head";
import Link from "next/link";
import Layout from "@/components/Layout";

//NY times API for fetching data
const API_KEY = "plbCTSLsncuKnvXzlc8Cf02XQkGGVuz6";

export default function News({ results, title }) {
  return (
    <Layout>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{title}</h1>
        <ul>
          {results?.map((result) => (
            <li key={result.url}>
              <Link href={result.url} rel="noopener noreferrer" target="_blank">
                {result.title}
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </Layout>
  );
}

export async function getStaticPaths() {
  const SECTIONS_URL = `https://api.nytimes.com/svc/news/v3/content/section-list.json?api-key=${API_KEY}`;
  const section_results = await handler(SECTIONS_URL);
  return {
    paths: section_results.map((result) => {
      return { params: { section: result.section } };
    }),
    fallback: true,
  };
}

//Prerender data on request time based on user input
export async function getStaticProps({ params }) {
  const TOP_STORIES_URL = `https://api.nytimes.com/svc/news/v3/content/nyt/${params.section}.json?api-key=${API_KEY}`;

  const results = await handler(TOP_STORIES_URL);
  return {
    props: {
      results,
      title: params.section,
    },
  };
}
