//Dynamic route

import { handler } from "../api/index";
import Head from "next/head";
import Link from "next/link";
import Layout from "@/components/Layout";

export default function Sections({ results, title }) {
  return (
    <Layout>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{title}</h1>
        <ul>
          {results?.map((result) => (
            <Link href={`sections/${result.section}`} rel="noopener noreferrer">
              {result.display_name}
            </Link>
          ))}
        </ul>
      </main>
    </Layout>
  );
}

//NY times API for fetching data
const API_KEY = "plbCTSLsncuKnvXzlc8Cf02XQkGGVuz6";

//Prerender data on request time based on user input
export async function getStaticProps() {
  const SECTIONS_URL = `https://api.nytimes.com/svc/news/v3/content/section-list.json?api-key=${API_KEY}`;

  return {
    props: {
      results: await handler(SECTIONS_URL),
      title: "Sections",
    },
  };
}
